import type { ExperienceItemType } from './../model/types'

export const experienceData: ExperienceItemType[] = [
  {
    company: 'Ongoing Product Development',
    period: '2025–н.в.',
    role: 'Product Engineer',
    stack: [
      'Next.js (App Router)',
      'TypeScript',
      'Tailwind CSS',
    ],
    description: 'ongoing.description',
    result: 'ongoing.resultDescription',
  },
  {
    company: 'DMZ Home Construct',
    period: '2025 · contract',
    role: 'Frontend / Full-Stack Engineer',
    stack: [
      'Next.js (App Router, ISR)',
      'TypeScript',
      'Payload CMS v3 (from scratch)',
      'Tailwind CSS',
    ],
    description: 'contract.description',
    result: 'contract.resultDescription',
  },
  {
    company: 'CPABOX',
    period: '2022–2025',
    role: 'Frontend / Full-Stack Engineer',
    stack: [
      'React',
      'Next.js',
      'NestJS',
      'TypeScript',
      'Zustand',
      'MUI',
      'ApexCharts',
      'Keitaro API',
      'Telegram Web App',
    ],
    description: 'cpabox.description',
    result: 'cpabox.resultDescription',
  },
  {
    company: 'Remotza.tech',
    period: '2021–2022',
    role: 'Backend / Full-Stack Developer',
    stack: [
      'Laravel',
      'Vue.js',
      'REST API',
      'PostgreSQL',
      'Redis',
    ],
    description: 'remotza.description',
    result: 'remotza.resultDescription',
  },
  {
    company: 'AOPSRM',
    period: '2020–2021',
    role: 'Full-Stack Developer',
    stack: [
      'React',
      'Laravel',
      'Docker',
      'GitLab CI/CD',
      'Multilingual CMS',
    ],
    description: 'aopsrm.description',
    result: 'aopsrm.resultDescription',
  },
]