export { TechnicalSkills } from './technical-skills/ui/TechnicalSkills'
export { Experience } from './experience/ui/Experience'
export { Education } from './education/Education'
export { Additional } from './additional/Additional'
export { Hero } from './hero/Hero'
export { Intro } from './intro/Intro'